# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fanGUI_Project.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wid_FanRecont(object):
    def setupUi(self, wid_FanRecont):
        wid_FanRecont.setObjectName("wid_FanRecont")
        wid_FanRecont.resize(856, 642)
        self.gridLayout = QtWidgets.QGridLayout(wid_FanRecont)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_Sinogram = QtWidgets.QFrame(wid_FanRecont)
        self.frame_Sinogram.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Sinogram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Sinogram.setObjectName("frame_Sinogram")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Sinogram)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Sino = QtWidgets.QLabel(self.frame_Sinogram)
        self.label_Sino.setObjectName("label_Sino")
        self.verticalLayout_2.addWidget(self.label_Sino)
        self.gV_Sinogram = QtWidgets.QGraphicsView(self.frame_Sinogram)
        self.gV_Sinogram.setAutoFillBackground(False)
        self.gV_Sinogram.setObjectName("gV_Sinogram")
        self.verticalLayout_2.addWidget(self.gV_Sinogram)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.frame_Sinogram, 2, 0, 1, 1)
        self.frame_Phantom = QtWidgets.QFrame(wid_FanRecont)
        self.frame_Phantom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Phantom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Phantom.setObjectName("frame_Phantom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_Phantom)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Phantom = QtWidgets.QLabel(self.frame_Phantom)
        self.label_Phantom.setObjectName("label_Phantom")
        self.verticalLayout_3.addWidget(self.label_Phantom)
        self.gV_Phantom = QtWidgets.QGraphicsView(self.frame_Phantom)
        self.gV_Phantom.setAutoFillBackground(False)
        self.gV_Phantom.setObjectName("gV_Phantom")
        self.verticalLayout_3.addWidget(self.gV_Phantom)
        self.hSlider_Phantom = QtWidgets.QSlider(self.frame_Phantom)
        self.hSlider_Phantom.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_Phantom.setObjectName("hSlider_Phantom")
        self.verticalLayout_3.addWidget(self.hSlider_Phantom)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.frame_Phantom, 0, 0, 1, 1)
        self.frame_Backproj = QtWidgets.QFrame(wid_FanRecont)
        self.frame_Backproj.setAutoFillBackground(True)
        self.frame_Backproj.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Backproj.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Backproj.setLineWidth(1)
        self.frame_Backproj.setObjectName("frame_Backproj")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Backproj)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Backproj = QtWidgets.QLabel(self.frame_Backproj)
        self.label_Backproj.setAutoFillBackground(True)
        self.label_Backproj.setObjectName("label_Backproj")
        self.verticalLayout.addWidget(self.label_Backproj)
        self.gV_Backproj = QtWidgets.QGraphicsView(self.frame_Backproj)
        self.gV_Backproj.setAutoFillBackground(False)
        self.gV_Backproj.setObjectName("gV_Backproj")
        self.verticalLayout.addWidget(self.gV_Backproj)
        self.hSlider_Backproj = QtWidgets.QSlider(self.frame_Backproj)
        self.hSlider_Backproj.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_Backproj.setObjectName("hSlider_Backproj")
        self.verticalLayout.addWidget(self.hSlider_Backproj)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame_Backproj, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_Select = QtWidgets.QFrame(wid_FanRecont)
        self.frame_Select.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Select.setObjectName("frame_Select")
        self.layoutWidget = QtWidgets.QWidget(self.frame_Select)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 299))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pB_PhantomSelect = QtWidgets.QPushButton(self.layoutWidget)
        self.pB_PhantomSelect.setObjectName("pB_PhantomSelect")
        self.verticalLayout_4.addWidget(self.pB_PhantomSelect)
        self.cBox_Filterselect = QtWidgets.QComboBox(self.layoutWidget)
        self.cBox_Filterselect.setObjectName("cBox_Filterselect")
        self.cBox_Filterselect.addItem("")
        self.cBox_Filterselect.addItem("")
        self.cBox_Filterselect.addItem("")
        self.verticalLayout_4.addWidget(self.cBox_Filterselect)
        self.horizontalLayout_4.addWidget(self.frame_Select)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.frame_Phantom.raise_()
        self.frame_Sinogram.raise_()
        self.frame_Backproj.raise_()

        self.retranslateUi(wid_FanRecont)
        QtCore.QMetaObject.connectSlotsByName(wid_FanRecont)

    def retranslateUi(self, wid_FanRecont):
        _translate = QtCore.QCoreApplication.translate
        wid_FanRecont.setWindowTitle(_translate("wid_FanRecont", "Fan Beam Reconstruction Interactive GUI"))
        self.label_Sino.setText(_translate("wid_FanRecont", "Sinogram"))
        self.label_Phantom.setText(_translate("wid_FanRecont", "Phantom"))
        self.label_Backproj.setText(_translate("wid_FanRecont", "Back Projection"))
        self.pB_PhantomSelect.setText(_translate("wid_FanRecont", "Select Phantom"))
        self.cBox_Filterselect.setItemText(0, _translate("wid_FanRecont", "Parker weighting"))
        self.cBox_Filterselect.setItemText(1, _translate("wid_FanRecont", "Ramp filter"))
        self.cBox_Filterselect.setItemText(2, _translate("wid_FanRecont", "Cosine weighting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wid_FanRecont = QtWidgets.QWidget()
    ui = Ui_wid_FanRecont()
    ui.setupUi(wid_FanRecont)
    wid_FanRecont.show()
    sys.exit(app.exec_())

