# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fanGUI_Project.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReconstructionGUI(object):
    def setupUi(self, ReconstructionGUI):
        ReconstructionGUI.setObjectName("ReconstructionGUI")
        ReconstructionGUI.resize(904, 682)
        self.Reconstruction = QtWidgets.QWidget(ReconstructionGUI)
        self.Reconstruction.setObjectName("Reconstruction")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Reconstruction)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pB_PhantomSelect = QtWidgets.QPushButton(self.Reconstruction)
        self.pB_PhantomSelect.setObjectName("pB_PhantomSelect")
        self.verticalLayout.addWidget(self.pB_PhantomSelect)
        self.label_Phantom = QtWidgets.QLabel(self.Reconstruction)
        self.label_Phantom.setObjectName("label_Phantom")
        self.verticalLayout.addWidget(self.label_Phantom)
        self.gV_Phantom = QtWidgets.QGraphicsView(self.Reconstruction)
        self.gV_Phantom.setAutoFillBackground(False)
        self.gV_Phantom.setObjectName("gV_Phantom")
        self.verticalLayout.addWidget(self.gV_Phantom)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pB_Xray = QtWidgets.QPushButton(self.Reconstruction)
        self.pB_Xray.setObjectName("pB_Xray")
        self.verticalLayout_2.addWidget(self.pB_Xray)
        self.label_Sino = QtWidgets.QLabel(self.Reconstruction)
        self.label_Sino.setObjectName("label_Sino")
        self.verticalLayout_2.addWidget(self.label_Sino)
        self.gV_Sinogram = QtWidgets.QGraphicsView(self.Reconstruction)
        self.gV_Sinogram.setAutoFillBackground(False)
        self.gV_Sinogram.setObjectName("gV_Sinogram")
        self.verticalLayout_2.addWidget(self.gV_Sinogram)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pB_Reconstruction = QtWidgets.QPushButton(self.Reconstruction)
        self.pB_Reconstruction.setObjectName("pB_Reconstruction")
        self.verticalLayout_3.addWidget(self.pB_Reconstruction)
        self.label_Backproj = QtWidgets.QLabel(self.Reconstruction)
        self.label_Backproj.setAutoFillBackground(True)
        self.label_Backproj.setObjectName("label_Backproj")
        self.verticalLayout_3.addWidget(self.label_Backproj)
        self.gV_Backproj = QtWidgets.QGraphicsView(self.Reconstruction)
        self.gV_Backproj.setAutoFillBackground(False)
        self.gV_Backproj.setObjectName("gV_Backproj")
        self.verticalLayout_3.addWidget(self.gV_Backproj)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_PhantomFFT = QtWidgets.QLabel(self.Reconstruction)
        self.label_PhantomFFT.setObjectName("label_PhantomFFT")
        self.verticalLayout_4.addWidget(self.label_PhantomFFT)
        self.gV_Phantom_FFT = QtWidgets.QGraphicsView(self.Reconstruction)
        self.gV_Phantom_FFT.setObjectName("gV_Phantom_FFT")
        self.verticalLayout_4.addWidget(self.gV_Phantom_FFT)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_ParkerWeigh = QtWidgets.QCheckBox(self.Reconstruction)
        self.checkBox_ParkerWeigh.setObjectName("checkBox_ParkerWeigh")
        self.verticalLayout_6.addWidget(self.checkBox_ParkerWeigh)
        self.checkBox_RamLakFilter = QtWidgets.QCheckBox(self.Reconstruction)
        self.checkBox_RamLakFilter.setObjectName("checkBox_RamLakFilter")
        self.verticalLayout_6.addWidget(self.checkBox_RamLakFilter)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_BackprojFFT = QtWidgets.QLabel(self.Reconstruction)
        self.label_BackprojFFT.setObjectName("label_BackprojFFT")
        self.verticalLayout_5.addWidget(self.label_BackprojFFT)
        self.gV_Backproj_FFT = QtWidgets.QGraphicsView(self.Reconstruction)
        self.gV_Backproj_FFT.setObjectName("gV_Backproj_FFT")
        self.verticalLayout_5.addWidget(self.gV_Backproj_FFT)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        ReconstructionGUI.setCentralWidget(self.Reconstruction)
        self.menubar = QtWidgets.QMenuBar(ReconstructionGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 26))
        self.menubar.setObjectName("menubar")
        ReconstructionGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReconstructionGUI)
        self.statusbar.setObjectName("statusbar")
        ReconstructionGUI.setStatusBar(self.statusbar)

        self.retranslateUi(ReconstructionGUI)
        QtCore.QMetaObject.connectSlotsByName(ReconstructionGUI)

    def retranslateUi(self, ReconstructionGUI):
        _translate = QtCore.QCoreApplication.translate
        ReconstructionGUI.setWindowTitle(_translate("ReconstructionGUI", "Reconstruction"))
        self.pB_PhantomSelect.setText(_translate("ReconstructionGUI", "Select Phantom"))
        self.label_Phantom.setText(_translate("ReconstructionGUI", "Phantom"))
        self.pB_Xray.setText(_translate("ReconstructionGUI", "X-Ray"))
        self.label_Sino.setText(_translate("ReconstructionGUI", "Sinogram"))
        self.pB_Reconstruction.setText(_translate("ReconstructionGUI", "Reconstruction"))
        self.label_Backproj.setText(_translate("ReconstructionGUI", "Back Projection"))
        self.label_PhantomFFT.setText(_translate("ReconstructionGUI", "Phantom FFT"))
        self.checkBox_ParkerWeigh.setText(_translate("ReconstructionGUI", "Parker Weighting"))
        self.checkBox_RamLakFilter.setText(_translate("ReconstructionGUI", "RamLak Filtering"))
        self.label_BackprojFFT.setText(_translate("ReconstructionGUI", "Backprojection FFT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReconstructionGUI = QtWidgets.QMainWindow()
    ui = Ui_ReconstructionGUI()
    ui.setupUi(ReconstructionGUI)
    ReconstructionGUI.show()
    sys.exit(app.exec_())

