# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fanGUI_Project.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wid_FanRecont(object):
    def setupUi(self, wid_FanRecont):
        wid_FanRecont.setObjectName("wid_FanRecont")
        wid_FanRecont.resize(869, 633)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(wid_FanRecont)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pB_PhantomSelect = QtWidgets.QPushButton(wid_FanRecont)
        self.pB_PhantomSelect.setObjectName("pB_PhantomSelect")
        self.verticalLayout.addWidget(self.pB_PhantomSelect)
        self.label_Phantom = QtWidgets.QLabel(wid_FanRecont)
        self.label_Phantom.setObjectName("label_Phantom")
        self.verticalLayout.addWidget(self.label_Phantom)
        self.gV_Phantom = QtWidgets.QGraphicsView(wid_FanRecont)
        self.gV_Phantom.setAutoFillBackground(False)
        self.gV_Phantom.setObjectName("gV_Phantom")
        self.verticalLayout.addWidget(self.gV_Phantom)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pB_Xray = QtWidgets.QPushButton(wid_FanRecont)
        self.pB_Xray.setObjectName("pB_Xray")
        self.verticalLayout_2.addWidget(self.pB_Xray)
        self.label_Sino = QtWidgets.QLabel(wid_FanRecont)
        self.label_Sino.setObjectName("label_Sino")
        self.verticalLayout_2.addWidget(self.label_Sino)
        self.gV_Sinogram = QtWidgets.QGraphicsView(wid_FanRecont)
        self.gV_Sinogram.setAutoFillBackground(False)
        self.gV_Sinogram.setObjectName("gV_Sinogram")
        self.verticalLayout_2.addWidget(self.gV_Sinogram)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pB_Reconstruction = QtWidgets.QPushButton(wid_FanRecont)
        self.pB_Reconstruction.setObjectName("pB_Reconstruction")
        self.verticalLayout_3.addWidget(self.pB_Reconstruction)
        self.label_Backproj = QtWidgets.QLabel(wid_FanRecont)
        self.label_Backproj.setAutoFillBackground(True)
        self.label_Backproj.setObjectName("label_Backproj")
        self.verticalLayout_3.addWidget(self.label_Backproj)
        self.gV_Backproj = QtWidgets.QGraphicsView(wid_FanRecont)
        self.gV_Backproj.setAutoFillBackground(False)
        self.gV_Backproj.setObjectName("gV_Backproj")
        self.verticalLayout_3.addWidget(self.gV_Backproj)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_PhantomFFT = QtWidgets.QLabel(wid_FanRecont)
        self.label_PhantomFFT.setObjectName("label_PhantomFFT")
        self.verticalLayout_4.addWidget(self.label_PhantomFFT)
        self.gV_Phantom_FFT = QtWidgets.QGraphicsView(wid_FanRecont)
        self.gV_Phantom_FFT.setObjectName("gV_Phantom_FFT")
        self.verticalLayout_4.addWidget(self.gV_Phantom_FFT)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_ParkerWeigh = QtWidgets.QCheckBox(wid_FanRecont)
        self.checkBox_ParkerWeigh.setObjectName("checkBox_ParkerWeigh")
        self.verticalLayout_6.addWidget(self.checkBox_ParkerWeigh)
        self.checkBox_RamLakFilter = QtWidgets.QCheckBox(wid_FanRecont)
        self.checkBox_RamLakFilter.setObjectName("checkBox_RamLakFilter")
        self.verticalLayout_6.addWidget(self.checkBox_RamLakFilter)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_BackprojFFT = QtWidgets.QLabel(wid_FanRecont)
        self.label_BackprojFFT.setObjectName("label_BackprojFFT")
        self.verticalLayout_5.addWidget(self.label_BackprojFFT)
        self.gV_Backproj_FFT = QtWidgets.QGraphicsView(wid_FanRecont)
        self.gV_Backproj_FFT.setObjectName("gV_Backproj_FFT")
        self.verticalLayout_5.addWidget(self.gV_Backproj_FFT)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.pB_PhantomSelect.raise_()
        self.pB_Xray.raise_()
        self.pB_Reconstruction.raise_()
        self.gV_Phantom_FFT.raise_()
        self.gV_Backproj_FFT.raise_()
        self.checkBox_ParkerWeigh.raise_()
        self.checkBox_RamLakFilter.raise_()
        self.label_PhantomFFT.raise_()
        self.label_BackprojFFT.raise_()
        self.gV_Sinogram.raise_()
        self.label_Sino.raise_()
        self.gV_Phantom.raise_()
        self.label_Phantom.raise_()
        self.gV_Backproj.raise_()
        self.label_Backproj.raise_()

        self.retranslateUi(wid_FanRecont)
        QtCore.QMetaObject.connectSlotsByName(wid_FanRecont)

    def retranslateUi(self, wid_FanRecont):
        _translate = QtCore.QCoreApplication.translate
        wid_FanRecont.setWindowTitle(_translate("wid_FanRecont", "Fan Beam Reconstruction Interactive GUI"))
        self.pB_PhantomSelect.setText(_translate("wid_FanRecont", "Select Phantom"))
        self.label_Phantom.setText(_translate("wid_FanRecont", "Phantom"))
        self.pB_Xray.setText(_translate("wid_FanRecont", "X-Ray"))
        self.label_Sino.setText(_translate("wid_FanRecont", "Sinogram"))
        self.pB_Reconstruction.setText(_translate("wid_FanRecont", "Reconstruction"))
        self.label_Backproj.setText(_translate("wid_FanRecont", "Back Projection"))
        self.label_PhantomFFT.setText(_translate("wid_FanRecont", "Phantom FFT"))
        self.checkBox_ParkerWeigh.setText(_translate("wid_FanRecont", "Parker Weighting"))
        self.checkBox_RamLakFilter.setText(_translate("wid_FanRecont", "RamLak Filtering"))
        self.label_BackprojFFT.setText(_translate("wid_FanRecont", "Backprojection FFT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wid_FanRecont = QtWidgets.QWidget()
    ui = Ui_wid_FanRecont()
    ui.setupUi(wid_FanRecont)
    wid_FanRecont.show()
    sys.exit(app.exec_())

